sandbox = false
experimental-features = pipe-operators nix-command flakes
substituters = https://niri.cachix.org https://cache.nixos.org/
trusted-public-keys = niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
