onboarding = false

[theme]
auto_switch = false
name = "catppuccin"

[theme.custom]
active_row_bg = "#181825"
sidebar_bg = "#181825"
surface_dim = "#181825"

[terminal]
default_shell = "nu"
kitty_graphics = true

[ui]
accent = "white"
hide_tab_bar_when_single_tab = true
host_cursor = "native"
pane_borders = "auto"
sidebar_start_collapsed = true
status_indicators = "dots"
tab_bar_position = "bottom"

[ui.toast.clipboard]
position = "bottom-right"

[ui.sidebar.spaces]
row_gap = 1

[ui.sidebar.agents]
row_gap = 1
rows = [
  ["state_icon", "state_text"],
  [{token = "agent", fg = "#cdd6f4", dim = false}, "workspace"],
  [{token = "terminal_title", fg = "#6c7086", dim = false}]
]

[ui.toast]
delivery = "herdr"

[keys]
prefix = "ctrl+space"
help = ["prefix+/", "prefix+?"]
toggle_sidebar = "prefix+space"
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"
previous_tab = "alt+shift+h"
next_tab = "alt+shift+l"
previous_workspace = "alt+shift+k"
next_workspace = "alt+shift+j"
split_vertical = ["prefix+v", "alt+n"]
new_tab = "alt+t"
new_workspace = "alt+w"
close_pane = "alt+c"
close_tab = "alt+q"
rename_tab = "alt+r"
rename_workspace = "alt+shift+r"
zoom = "alt+shift+f"
goto = "alt+s"
copy_mode = "prefix+y"
open_worktree = "prefix+c"
new_worktree = "prefix+shift+c"
remove_worktree = "prefix+d"

[[keys.command]]
key = "prefix+f"
type = "popup"
command = "nu -c 'with-env { ESCAPE_MODE: floating } { nu }'"
description = "open floating terminal"

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "drydock"
description = "open list of repos"
width = "80%"

[[keys.command]]
key = "prefix+n"
type = "popup"
command = "leaf $ZK_NOTEBOOK_DIR"
description = "open notes"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "tuxedo"
description = "open tasks"
width = "80%"
height = "80%"

[worktrees]
directory = "~/repos/worktrees"
