[accessibility]
ui_scale = 1.1000000089406967

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    capsule_radius = 4
    center = [ "workspaces" ]
    end = [
        "tray",
        "clipboard",
        "screenshot",
        "theme_mode",
        "spacer_1",
        "notifications",
        "network",
        "spacer_2",
        "keyboard_layout",
        "volume",
        "brightness",
        "battery",
        "spacer_3",
        "session"
    ]
    margin_ends = 0
    padding = 8
    position = "bottom"
    radius = 4
    start = [ "launcher", "custom_button_2", "clock", "date" ]
    thickness = 40

        [bar.default.dead_zone.actions]
        left = "panel-toggle control-center home"
        right = "panel-toggle control-center media"

[battery]
warning_threshold = 15

[control_center]
show_shortcut_labels = false
sidebar = "full"
sidebar_section = "full"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "audio"

    [[control_center.shortcuts]]
    type = "clipboard"

    [[control_center.shortcuts]]
    type = "keyboard_layout"

    [[control_center.shortcuts]]
    type = "session"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000002" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 80.0
    box_width = 256.0
    cx = 960.0
    cy = 188.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        center_text = false
        clock_style = "digital"
        color = "on_surface"
        format = "{:%H:%M:%S}"
        timezone = ""

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 474.5
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "calendar"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = true
        show_events = false
        show_week_numbers = false

[shell]
app_icon_colorize = true
button_borders = false
card_borders = false
clipboard_history_max_entries = 10
corner_radius_scale = 0.5000000074505806
font_family = "CaskaydiaCove Nerd Font"
input_borders = false
niri_overview_type_to_launch_enabled = true
offline_mode = true
polkit_agent = true
popup_borders = false
time_format = "{:%H:%M:%S}"

    [shell.animation]
    speed = 1.5000000223517418

    [shell.keyboard_layout.custom_labels]
    "English (Canada)" = "EN"
    "French (Canada)" = "FR"

    [shell.launcher]
    categories = false
    compact = false
    fetch_exchange_rates = false
    pinned = []
    show_app_actions = true
    show_icons = false

        [shell.launcher.providers.session]
        global = true

        [shell.launcher.providers.windows]
        global = true

    [shell.panel]
    borders = false
    control_center_placement = "floating"
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = true
    size = 4

    [shell.session]
    grid = true
    grid_columns = 2
    show_shortcuts = false

    [shell.shadow]
    direction = "down_right"

[system.monitor]
enabled = false

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Mocha Blue"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "alacritty" ]
    community_ids = [ "spicetify", "zen-browser" ]
    enable_community_templates = true

[wallpaper]
directory = "/home/thom/.config/wallpaper"
fill_color = "on_primary"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/thom/.config/wallpaper/catppuccin.jpg"

    [wallpaper.last]
    path = "/home/thom/.config/wallpaper/catppuccin.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/thom/.config/wallpaper/catppuccin.jpg"

[widget.clock]
capsule = true
capsule_fill = "primary"
capsule_foreground = "on_primary"
format = "{:%H:%M:%S}"

[widget.custom_button_2]
glyph = "terminal"
tooltip = "Terminal"
type = "custom_button"

    [widget.custom_button_2.actions]
    left = "exec alacritty"
    middle = "none"

[widget.date]
capsule_radius = 4
format = "{:%y-%m-%d}"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.spacer_1]
type = "spacer"

[widget.spacer_2]
type = "spacer"

[widget.spacer_3]
type = "spacer"

[widget.taskbar]
only_active_workspace = true

[widget.workspaces]
active_pill_size = 2.0
capsule = true
capsule_fill = "surface"
focused_color = "primary"
occupied_color = "secondary"
pill_scale = 0.5
scale = 1.5
show_labels = false
style = "regular"
