customCommands:
  - command: 'git checkout master; git pull --prune'
    context: localBranches
    key: 'C'
git:
  branchLogCmd: git log --pretty=format:"%C(brightwhite)%s%Creset%n%C(yellow)%ar%Creset - %C(cyan)%ae%Creset%n" --color=always --stat --
gui:
  nerdFontsVersion: '2'
  showBottomLine: false
  showPanelJumps: false
  showRandomTip: false
  statusPanelView: allBranchesLog
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
      - bold
    selectedLineBgColor:
      - "#3e4452" # set to `default` to have no background colour
  timeFormat: '2006-01-02 / 15h04m'
notARepository: 'skip'
os:
  edit: 'hx {{filename}}'
  editAtLine: 'hx +{{line}} {{filename}}'
  editInTerminal: true
  openDirInEditor: 'hx {{dir}}'
  open: '~/.config/broot/open.sh {{filename}}'
  openLink: 'wslview {{link}}'
