# Ordering overrides for the ExcaliDash units generated by
# `virtualisation.oci-containers`.
#
# `mkForce` is required to drop the `wants`/`after` entries the oci-containers
# module sets by default (network-online.target, multi-user.target); the
# containers need the network to exist *before* they are pulled and started, and
# must be stopped before the docker daemon goes away.
{
  lib,
  pkgs,
  ...
}:
{
  systemd.services.docker-excalidash-backend = {
    wants = lib.mkForce [ ];
    after = lib.mkForce [
      "docker.service"
      "docker.socket"
      "init-excalidash-network.service"
      "multi-user.target"
    ];
    before = lib.mkForce [ "shutdown.target" ];
    requires = [ "init-excalidash-network.service" ];
    serviceConfig.ExecStartPre = lib.mkBefore [
      "${pkgs.coreutils}/bin/rm -rf /var/lib/excalidash/.migration-lock"
    ];
  };

  systemd.services.docker-excalidash-frontend = {
    wants = lib.mkForce [ ];
    after = lib.mkForce [
      "docker.service"
      "docker.socket"
      "docker-excalidash-backend.service"
      "init-excalidash-network.service"
      "multi-user.target"
    ];
    before = lib.mkForce [ "shutdown.target" ];
    requires = [ "init-excalidash-network.service" ];
  };
}
