add_newline = true

format = """
 [$directory](bright-white)\
$kubernetes\
$azure\
$git_status
$env_var$nix_shell$character"""

[env_var.PROMPT_EXTRA]
style = 'italic purple'
variable = 'PROMPT_EXTRA'
format = '[ $env_value]($style)'

[nix_shell]
style = 'italic cyan'
format = '[ nix]($style)'

[character]
success_symbol = ' [->](bright-white)'
error_symbol = ' [|>](red)'

[directory]
style = 'blue'
format = '[$path]($style)'
fish_style_pwd_dir_length = 1

[kubernetes]
style = 'green'
symbol = ''
format = ' [\[[$symbol$context([/](bright-white)[$namespace](purple))]($style)\]](bright-white)'
disabled = false

[[kubernetes.contexts]]
context_pattern = '.*prod.*'
style = 'red'

[azure]
style = 'yellow'
symbol = ''
format = ' [\[[$symbol$subscription]($style)\]](bright-white)'
disabled = false

[git_status]
style = 'red'
deleted = 'x'
diverged = '[⇡⇣](purple)'
up_to_date = '[](green)'
format = ' [\[[$all_status$ahead_behind]($style)\]](bright-white)'
