[language-server]
none = { command = "" }

# C#
omnisharp = { command = "OmniSharp", args = ["--languageserver"] }

# HTML
vscode-esling-language-server = { command = "vscode-eslint-language-server", args = ["stdio"], config = { experimental = { useFlatConfig = true }, workingDirectory = { mode = "auto" }}}

# Java
jdtls = { command = "jdtls", args = ["--jvm-arg=-javaagent:/home/thomas/.config/helix/java/lombok-1.18.32.jar"] }

# Markdown
vale = { command = "vale-ls" }

# YAML
yaml = { command = "yaml-language-server", args = ["--stdio"], config = { yaml = { format = { enable = true }, keyOrdering = false } } } # https://github.com/redhat-developer/yaml-language-server#language-server-settings

[[language]]
name = "bash"
language-servers = ["none"]

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]

[[language]]
name = "html"
auto-format = false

[[language]]
name = "css"
auto-format = false

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
language-servers = [ "marksman", "markdown-oxide", "vale" ]
diagnostic-severity = "warning"

[[language]]
name = "nu"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "python"
auto-format = false
indent = { tab-width = 4, unit = "	" }
formatter = { command = "black", args = ["-", "-l160"]}

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = ["yaml"]
auto-format = false
formatter = { command = "prettier", args = ["--parser", "yaml"] }
